### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by tibormucha** [MCMicS/jenkins-control-plugin#107]
null
java.lang.NullPointerException
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:175)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createViewJobs(JenkinsJsonParser.java:296)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:124)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:239)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:457)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$700(BrowserPanel.java:65)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:565)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by tjkierzkowski** [comment]
Had the exact same issue happen to me today.  I was wondering if it had anything to do with the [CloudBees Folder Plugin](https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin)?  I noticed this pulled the jobs from the other views that have only jobs within it. Once I added a Folder item in the view, the jobs would not load with the same error.

**Comment by c0untzer0** [comment]
Apparently there's a pull request for a fix to this issue (I'm also having it), but it has one conflict and has not been pulled in. Anybody taking care of this?

**Comment by nickgrealy** [comment]
+1 Having the same issue.

@c0untzer0 - which pull request are you talking about? There's only [one open pull request](https://github.com/dboissier/jenkins-control-plugin/pull/108), and it has no merge conflicts (atm).

**Comment by c0untzer0** [comment]
@nickgrealy - The one open pull request with commits from @cezary-butler has the fixes if I remember correctly. Unfortunately it hasn't been merged in all this time.

**Comment by dboissier** [comment]
Hi,

I will release a version by this end of this week.

Many thanks for your patience.

**Comment by ocrosby** [comment]
Any fixes for this, I just ran into it while attempting to try out the plugin for the first time.

**Comment by MCMicS** [comment]
close this because it seems fixed
If any error occurs please report a new issue
