### ISSUE TITLE
java.lang.IllegalStateException: Empty JSON data

### ISSUE THREAD

**Issue by tabbed7** [MCMicS/jenkins-control-plugin#109]
I get an Exception when i try to use your Jenkins Plugin

Empty JSON data!

java.lang.IllegalStateException: Empty JSON data!
               at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.checkJsonDataAndThrowExceptionIfNecessary(JenkinsJsonParser.java:345)
               at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createWorkspace(JenkinsJsonParser.java:36)
               at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsWorkspace(RequestManager.java:83)
               at org.codinjutsu.tools.jenkins.logic.LoginService$1.run(LoginService.java:61)
               at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
               at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
               at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
               at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
               at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
               at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
               at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
               at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
               at java.lang.Thread.run(Thread.java:745)
               at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

My steps:
-        configured my Jenkins server
-        tested connection
-        clicked OK
-        Error occured
-        now it also would occur every time when i start Intellij (I disabled the plugin already)

My IDE: Intellij IDEA 15.0.1

Regards,
Phil

**Comment by cezary-butler** [comment]
This is duplicate of #93 (exception is different due to changes introduced by David) .
Plugin can't work when jenkins doesn't provide any data for it.
We would need access to your server to diagnose why it responds with `{}`.
