### ISSUE TITLE
org.json.simple.JSONObject cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by autoscatto** [MCMicS/jenkins-control-plugin#110]
I get an Exception on PyCharm (_PyCharm Community Edition 5.0.2, Build PC-143.1184_)
**org.json.simple.JSONObject cannot be cast to java.lang.String**

Details:

org.json.simple.JSONObject cannot be cast to java.lang.String
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to java.lang.String
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getChoices(JenkinsJsonParser.java:230)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getParameters(JenkinsJsonParser.java:216)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:182)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createViewJobs(JenkinsJsonParser.java:296)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:124)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:239)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:457)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$700(BrowserPanel.java:65)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:565)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

reproducibility: everytime, after configuration (and successful Test Connection) on "Loading Jenkins Jobs" phase the exception is thrown

Regards,
Autoscatto

**Comment by dboissier** [comment]
Hi,

Snapshots are available (see the [home page](https://github.com/dboissier/jenkins-control-plugin) of the project to get it depending on your IDE version).

Please tell me if it works on your IDE.

Thanks.

**Comment by autoscatto** [comment]
Same error on jenkins-control-plugin-0.9.5-SNAPSHOT on PyCharm Community Edition 2016.1.4
Build #PC-145.1504

org.json.simple.JSONObject cannot be cast to java.lang.String
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to java.lang.String
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getChoices(JenkinsJsonParser.java:233)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getParameters(JenkinsJsonParser.java:219)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:185)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createViewJobs(JenkinsJsonParser.java:283)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:124)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:239)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:457)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$700(BrowserPanel.java:65)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:565)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks in advance for the effort.
