### ISSUE TITLE
Unsupported Major.Minor version error starting IntelliJ with Jenkins Plugin

### ISSUE THREAD

**Issue by dbmcpheeters** [MCMicS/jenkins-control-plugin#112]
On OSX
Running IntelliJ Idea 14.0.3
Build #IC-139.1117, built on January 21, 2015

JRE: 1.6.0_45-b06-451-11M4609 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple,Inc.

Caused by: com.intellij.diagnostic.PluginException: org/codinjutsu/tools/jenkins/JenkinsComponent : Unsupported major.minor version 51.0 [Plugin: Jenkins Control Plugin] [Plugin: Jenkins Control Plugin]
    ... 28 more
Caused by: com.intellij.diagnostic.PluginException: org/codinjutsu/tools/jenkins/JenkinsComponent : Unsupported major.minor version 51.0 [Plugin: Jenkins Control Plugin]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.loadClasses(ComponentManagerImpl.java:426)
    ... 25 more
Caused by: java.lang.UnsupportedClassVersionError: org/codinjutsu/tools/jenkins/JenkinsComponent : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:213)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:209)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:185)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 31 more

**Comment by dboissier** [comment]
The plugin is now built with Java 7. This is why you have this error

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
