### ISSUE TITLE
Argument for @NotNull parameter 'htmlBody'

### ISSUE THREAD

**Issue by diegocr** [MCMicS/jenkins-control-plugin#127]
Getting the following exception under:

Jenkins: 1.642.3
Jenkins Control Plugin: 0.9.7

WebStorm 2016.2.3
Build #WS-162.1812.21, built on September 4, 2016
JRE: 1.8.0_112-release-b343 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

``` bash
Argument for @NotNull parameter 'htmlBody' of com/intellij/openapi/wm/impl/ToolWindowManagerImpl.notifyByBalloon must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'htmlBody' of com/intellij/openapi/wm/impl/ToolWindowManagerImpl.notifyByBalloon must not be null
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.notifyByBalloon(ToolWindowManagerImpl.java)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$6.run(BrowserPanel.java:322)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:829)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Drakhunter** [comment]
I still get this error. Any updates?

PhpStorm 2019.2.4
Build #PS-192.7142.41, built on October 30, 2019
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 972M
Cores: 8
