### ISSUE TITLE
Folders are not supported

### ISSUE THREAD

**Issue by svscorp** [MCMicS/jenkins-control-plugin#128]
In Jenkins it's quite common to see CloudBees Folders Plugin being used to structure projects. If there is at least one folder present - Jenkins Control Plugin causing exception:

`
null
java.lang.NullPointerException
    at org.codinjutsu.tools.jenkins.model.Build.getStateIcon(Build.java:87)
    at org.codinjutsu.tools.jenkins.model.Job.getStateIcon(Job.java:75)
    at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.customizeCellRenderer(JenkinsTreeRenderer.java:64)
    at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:116)
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
    at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1496)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:365)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$4.run(BrowserPanel.java:203)
    at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.setSortedByStatus(BrowserPanel.java:200)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.fillJobTree(BrowserPanel.java:497)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$900(BrowserPanel.java:65)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob$1.run(BrowserPanel.java:581)
    at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.onSuccess(BrowserPanel.java:578)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1$2.run(ProgressManagerImpl.java:153)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

It can be related to #115

**Comment by Scrayos** [comment]
I can confirm this.

**Comment by svscorp** [comment]
@dboissier Hi David, is there a chance you can have a look for this feature? I think folders are widely used nowadays. Though I can imagine it will require some interface changes as well expand/collapse functionality, more requests to Jenkins (if do lazy load on expand).

It's a very cool plugin. Would be happy to use it :)

**Comment by dboissier** [comment]
Hi,

thanks to Github contributors, new builds for Idea-15 and Idea-2016 are available on the home page of the project.

Please tell me whether it fixes the encountered issue.

Thanks for your patience.

**Comment by VVMichaelSawyer** [comment]
I am not getting a NullPointerException, but there still is no visibility into the jobs that exist within the folders. At this point I think it would be more of an `enhancement` than a `bug`.

**Comment by Harryson** [comment]
This feature would be nice!

**Comment by RobertLos** [comment]
I support this request for feature. We use the folders plugin quite extensively.

**Comment by dboissier** [comment]
Hi all,

I currently do not have any bandwidth for enhancing this plugin (probably more during July or August) unless some crazy developers submit a pull request ;).

Sorry for the inconvenience.

**Comment by javaking2013** [comment]
I too would like to see folder support.  You can get around this by setting the URL to the specific folder instead of the base Jenkins server.  The only drawback would be that you can't navigate to other folders.  In my case that doesn't matter.

**Comment by dstaflund** [comment]
I am just writing to express my support for this request -- the plugin isn't helpful right now for lack of folder support.

**Comment by GhaTMA** [comment]
+1

**Comment by igreenfield** [comment]
I also need this feature

**Comment by Suganthi06** [comment]
i need this feature too

**Comment by MCMicS** [comment]
should be solved with #141
