### ISSUE TITLE
error when trying to load builds Intellij 2017.3

### ISSUE THREAD

**Issue by Narimm** [MCMicS/jenkins-control-plugin#155]
```
org.codinjutsu.tools.jenkins.model.Build cannot be cast to org.codinjutsu.tools.jenkins.model.Job
java.lang.ClassCastException: org.codinjutsu.tools.jenkins.model.Build cannot be cast to org.codinjutsu.tools.jenkins.model.Job
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$1.compare(BrowserPanel.java:99)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$1.compare(BrowserPanel.java:96)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.util.ui.tree.TreeUtil.sortChildren(TreeUtil.java:313)
	at com.intellij.util.ui.tree.TreeUtil.sortRecursively(TreeUtil.java:303)
	at com.intellij.util.ui.tree.TreeUtil.sortRecursively(TreeUtil.java:306)
	at com.intellij.util.ui.tree.TreeUtil.sort(TreeUtil.java:299)
	at com.intellij.util.ui.tree.TreeUtil.sort(TreeUtil.java:295)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.setSortedByStatus(BrowserPanel.java:206)
	at org.codinjutsu.tools.jenkins.view.action.settings.SortByStatusAction.setSelected(SortByStatusAction.java:49)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:344)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by MCMicS** [comment]
closed by#143
