### ISSUE TITLE
NullPointerException when trying to load builds (IntelliJ Version : 2017.3)

### ISSUE THREAD

**Issue by stessy** [MCMicS/jenkins-control-plugin#157]
Hi,

just downloaded and installed the plugin.
When I try to load all the builds from a job I get the following error:

`null
java.lang.NullPointerException
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getBuilds(JenkinsJsonParser.java:189)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createBuilds(JenkinsJsonParser.java:150)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadBuilds(RequestManager.java:172)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadBuilds(RequestManager.java:254)
	at org.codinjutsu.tools.jenkins.view.action.LoadBuildsAction$1.run(LoadBuildsAction.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Is there a problem with the plugin for the latest version of IntelliJ?

Thanks for your help.
Kind regards,
Stessy

**Comment by Radiergummi** [comment]
Yup, exact same problem over here
