### ISSUE TITLE
Empty XML data

### ISSUE THREAD

**Issue by OrangeDog** [MCMicS/jenkins-control-plugin#194]
This popped up in IDEA 2019.3.4. Jenkins server is 2.204.5.

```
java.lang.IllegalStateException: Empty XML data
	at org.codinjutsu.tools.jenkins.logic.RssParser.buildDocument(RssParser.java:59)
	at org.codinjutsu.tools.jenkins.logic.RssParser.loadJenkinsRssLatestBuilds(RssParser.java:52)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsRssLatestBuilds(RequestManager.java:117)
	at org.codinjutsu.tools.jenkins.logic.RssLogic.loadAndReturnNewLatestBuilds(RssLogic.java:91)
	at org.codinjutsu.tools.jenkins.logic.RssLogic.access$000(RssLogic.java:48)
	at org.codinjutsu.tools.jenkins.logic.RssLogic$LoadLatestBuildsJob.run(RssLogic.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MCMicS** [comment]
Can you check if your jenkins deliver RSS feed?

```
JenkinsUrl/rssAll
```

I've see this on jenkins-ci without logged-in user . No RSS was available there.

**Comment by OrangeDog** [comment]
It does yeah. I think this was probably during a Jenkins restart, so it would've got a 503 / getting ready message.

**Comment by MCMicS** [comment]
So it works now?

Seems related to #65.

We should implement a better handling for that.

**Comment by MCMicS** [comment]
will fixed with #109
