### ISSUE TITLE
NullPointerException when "Show log" is clicked and Job Url is used as Server Address

### ISSUE THREAD

**Issue by tillias** [MCMicS/jenkins-control-plugin#195]
Hello,

I'm using 0.12.0-2019.3 version of plugin and get following exception when "Show logs" is clicked:

`java.lang.NullPointerException
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadConsoleTextFor(RequestManager.java:296)
	at org.codinjutsu.tools.jenkins.view.action.ShowLogAction$1.run(ShowLogAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Can you please advise if this is known issue?

**Comment by MCMicS** [comment]
not yet but I have a look at this.
Found  a possible reason for this.
 could you please attach a screen shot of your jenkins Panel?
This should happen if no job is found or no build was completed

**Comment by tillias** [comment]
![image](https://user-images.githubusercontent.com/753889/79252760-67c47d00-7e82-11ea-8129-1e81b42d6e49.png)

**Comment by tillias** [comment]
I have tried during build and after build -> in both use-cases there is NPE

**Comment by MCMicS** [comment]
OK thanks.
I currently reproduce it. But found the possible NPE, But a test is better to verify this :)

**Comment by MCMicS** [comment]
How do you create the view in Jenkins?
I see first a folder (or Github Organisation) with '»' in Name.

**Comment by tillias** [comment]
It is https://sbs.t-systems.com/jenkins/job/project-name in Settings -> Jenkins Plugin -> Server Address

Then inside Jenkins view it is displayed like Jenkins -> project-name » repo-name (bitbucket)

**Comment by tillias** [comment]
So it is like this (if compared to screenshot)
Jenkins
  project-name >> bitbucket-project
    project-name >> bitbucket-project >> git repo
      ... >> master

**Comment by MCMicS** [comment]
What if you use server url in settings?
https://buildsrv/jenkins

Because the Jobs and view are loaded from plugin

**Comment by tillias** [comment]
Then it works, but there are many many other projects, so refresh is slow. Will automatic refresh collapse all the items in the list?

**Comment by MCMicS** [comment]
currently yes.
I will implement to keep the collapse state later

thanks for feedback. So I have to look why use job url works and result in this error

**Comment by tillias** [comment]
Sure, I like the plugin, very impressive work done. Please let me know if I can help somehow with feedback, logs whatever. Vielen Dank.

**Comment by MCMicS** [comment]
Thanks. The previous developer had implement this nice plugin and I will do my best to maintain it because I like it too.

Now I try to reproduce it with Job URL as Server Address.

**Comment by MCMicS** [comment]
Now I can reproduce this.
Thansk for the hint with the wrong server URL. I have a look to fix this.
