### ISSUE TITLE
NumberFormatException from Build.createBuildFromRss

### ISSUE THREAD

**Issue by znerd** [MCMicS/jenkins-control-plugin#207]
```
java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.codinjutsu.tools.jenkins.model.Build.createBuildFromRss(Build.java:60)
	at org.codinjutsu.tools.jenkins.logic.RssParser.createLatestBuildList(RssParser.java:89)
	at org.codinjutsu.tools.jenkins.logic.RssParser.loadJenkinsRssLatestBuilds(RssParser.java:53)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsRssLatestBuilds(RequestManager.java:119)
	at org.codinjutsu.tools.jenkins.logic.RssLogic.loadAndReturnNewLatestBuilds(RssLogic.java:91)
	at org.codinjutsu.tools.jenkins.logic.RssLogic$LoadLatestBuildsJob.run(RssLogic.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Screenshot:
![Screen Shot 2020-05-07 at 15 03 20](https://user-images.githubusercontent.com/117866/81297692-f4beb880-9073-11ea-8b8a-b931df555f96.png)

**Comment by MCMicS** [comment]
seems duplicate #64

**Comment by znerd** [comment]
Yes, duplicate indeed! Closing.

**Comment by MCMicS** [comment]
Are you using the Version Number Plug-In?

**Comment by znerd** [comment]
@MCMicS : Here you go (I've done some search-and-replaces):

- [rss.xml.txt](https://github.com/MCMicS/jenkins-control-plugin/files/4594462/rss.xml.txt)

**Comment by MCMicS** [comment]
thanks
I wil lhave look at this
