### ISSUE TITLE
Can't get progress

### ISSUE THREAD

**Issue by Marat-Gumerov** [MCMicS/jenkins-control-plugin#235]
Looks like everything works fine. But I see lots of IDE fatal errors with this stack trace:
```
java.lang.RuntimeException: Can't get progress
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:230)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: com.intellij.util.IncorrectOperationException: Sorry but parent: Project (name=Aspose.Email.Cloud, containerState=DISPOSE_COMPLETED, componentStore=D:\dev\cloud)  has already been disposed (see the cause for stacktrace) so the child: null 303019072: running=false; canceled=false; task=null will never be disposed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:227)
	... 4 more
Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: Project (name=Aspose.Email.Cloud, containerState=DISPOSE_COMPLETED, componentStore=D:\dev\cloud)  has already been disposed (see the cause for stacktrace) so the child: null 303019072: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:61)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:65)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:90)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:75)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:49)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:45)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:41)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$runProcessWithProgressAsynchronously$2(ProgressManagerImpl.java:109)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.util.concurrency.PlainEdtExecutor.execute(PlainEdtExecutor.java:15)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runAsynchronously(CoreProgressManager.java:351)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:338)
	at com.intellij.openapi.progress.Task.queue(Task.java:109)
	at org.codinjutsu.tools.jenkins.util.GuiUtil$TaskRunner.run(GuiUtil.java:69)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by MCMicS** [comment]
Do you work with multiple open projects?
Or close an existing project and open a new one
 we have an issue for this (still working on this): #186

**Comment by Marat-Gumerov** [comment]
> Do you work with multiple open projects?
Yes, I do.

> we have an issue for this (still working on this): #186
Sorry, looks like I created a duplicate (

**Comment by MCMicS** [comment]
its ok. Better to report them twice but do nothing 😄

**Comment by MCMicS** [comment]
Duplicate of: #186, #211
