### ISSUE TITLE
Plugin 'Jenkins Control Plugin' failed to initialize in Android Studio >4.1

### ISSUE THREAD

**Issue by chenyanmo** [MCMicS/jenkins-control-plugin#247]
java.lang.UnsupportedClassVersionError: org/codinjutsu/tools/jenkins/ChangesBarProjectComponent has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.openapi.project.ProjectLoadHelper$Companion.registerComponents(projectLoader.kt:29)
    at com.intellij.openapi.project.ProjectLoadHelper.registerComponents(projectLoader.kt)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:323)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.convertAndLoadProject(PlatformProjectOpenProcessor.kt:404)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.prepareProject(PlatformProjectOpenProcessor.kt:299)
    at com.intellij.platform.PlatformProjectOpenProcessorKt.access$prepareProject(PlatformProjectOpenProcessor.kt:1)
    at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:186)
    at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:57)
    at com.intellij.platform.ProjectUiFrameAllocator$run$1$progressTask$1.run(ProjectFrameAllocator.kt:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:482)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:77)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by MCMicS** [comment]
thanks for report.
I will look for this. In my opionion Android studio should run with JBR 11 (Java 11 Runtime)

**Comment by MCMicS** [comment]
![grafik](https://user-images.githubusercontent.com/4604206/93620479-560b7680-f9da-11ea-8b51-0620c9e65276.png)
 In my installation the correct java version is used for class files.

@chenyanmo Which version do you have installed?
Do you install from marketplace or from zip. which zip do you use?

**Comment by MCMicS** [comment]
@chenyanmo I checked it again. Neither the marketplace version nor the zip in giuthub (2019.3 Build) has the wrong class version.

lease try again to install and reopen if problem still exists

**Comment by MCMicS** [comment]
Failed To load on Android Studio 4.1 RC
Android Studio 4.1 RC 3
Build #AI-201.8743.12.41.6823847, built on September 10, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by MCMicS** [comment]
The newer Android stil lus JBR8 but newer Jenkins plugin is build for Java 11
Either I build an JDK8 Version or you have to configure Android Studio to run with JBR11
https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under?page=3

**Comment by MCMicS** [comment]
Android Studio seem to bundled with JBR11. So the plugin is working on this platform

**Comment by MCMicS** [comment]
@chenyanmo Can you give following a try please?
https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/99382

**Comment by MCMicS** [comment]
@chenyanmo Could you please test following eap?
https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/99383

**Comment by MCMicS** [comment]
released with released with [0.13.9](../releases/tag/v0.13.9)
