### ISSUE TITLE
Internal Server Error when using IntelliJ 2020.3

### ISSUE THREAD

**Issue by sam33r786** [MCMicS/jenkins-control-plugin#257]
I have tried to use the plugin on IntelliJ (v. 2020.3) to connect to my Jenkins instance (v. 2.267).

When I try to test the connection I get the error: "Server Internal Error: Server unavailable"

org.codinjutsu.tools.jenkins.security.AuthenticationException: Server Internal Error: Server unavailable
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.checkResponse(DefaultSecurityClient.java:149)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.runMethod(DefaultSecurityClient.java:114)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.execute(DefaultSecurityClient.java:70)
	at org.codinjutsu.tools.jenkins.security.SecurityClient.execute(SecurityClient.java:33)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsRssLatestBuilds(RequestManager.java:121)
	at org.codinjutsu.tools.jenkins.logic.RssLogic.loadAndReturnNewLatestBuilds(RssLogic.java:89)
	at org.codinjutsu.tools.jenkins.logic.RssLogic.access$000(RssLogic.java:48)
	at org.codinjutsu.tools.jenkins.logic.RssLogic$LoadLatestBuildsJob.run(RssLogic.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MCMicS** [comment]
Hi,
thanks for it. I will have a look but my Installations currently works with latest version

Could you please check if the is running on that or domain.


The log says that rss fails. Could you also try to use curl to the jenkins

**Comment by MCMicS** [comment]
@sam33r786 Is the issue still existing?

can you use cUrl and post result?
```curl
curl -v --user name:token http://localhost:8080/api/json
curl -v --user name:token http://localhost:8080/api/json?tree=nodeName,nodeDescription,primaryView%5Bname,url%5D,views%5Bname,url,views%5Bname,url%5D%5D
```
 or use http file in IntelliJ:
```
### Successful test: check response status is 200
GET https://localhost:8443/api/json?tree=nodeName
Authorization: Basic {{username}} {{token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET https://localhost:8443/api/json?tree=nodeName,nodeDescription,primaryView%5Bname,url%5D,views%5Bname,url,views%5Bname,url%5D%5D
Authorization: Basic {{username}} {{token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###
```

**Comment by sam33r786** [comment]
> Host: http
> Authorization: Basic c2phaGFuZ2lyOjExZmQzYmEyYzlkNGVjNWMzODQ4ZmEyZTkxYjA3MWQxOWY=
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Server: nginx
< Date: Mon, 07 Dec 2020 14:05:32 GMT
< Transfer-Encoding: chunked
< Connection: close
< Location: http://advancedsearch2.virginmedia.com/dnserror.html
< Expires: Mon, 07 Dec 2020 14:15:32 GMT
< Cache-Control: max-age=600
< X-Frame-Options: DENY

This is the out put from the curl command. I should mention also that our Jenkins instance is set up on a remote machine.

**Comment by MCMicS** [comment]
In the curl result i firstly saw the dnerror page is return with http status 302.

Could you please verify the jenkins adress with the configured value within jenskins (Manage Jenkins-> System setting)

And please try it in a browser and compare the urls

Regards

**Comment by sam33r786** [comment]
Just checked and yes there was indeed a typo in the URL. I've tried again and now I'm just getting 

"curl: (7) Failed to connect to XXXXX. Connection refused."

Is this something to do with my Jenkins config?

**Comment by MCMicS** [comment]
it seems on first look.
If possible I can take a look at your machine (remote)

If it is not possible I need the curl result again
if you join gitter we can alos chat private if you you have sensible data

Try following steps:
1 Goto to your Jenkins
2 Login and goto `http://127.0.0.1:8080/configure`
3 Use the given `Jenkins Location` as Url

if not work try curl again:
```
http://127.0.0.1:8080/api/json?tree=url
```

**Comment by sam33r786** [comment]
Unfortunately I highly doubt I would get the necessary approval for you to have a look at the machine. Are there any particular settings that I should check before I curl again?

**Comment by MCMicS** [comment]
Only the url of your jenkins instance (in manage jenkins if you have access)
Do you use an openshift jenkins version with sso. Because we currently have no support SSO


Did the jenkins before 2020.3 or it is the first test against this jenkins?

**Comment by MCMicS** [comment]
@sam33r786 have you any news? Do you need more help to find the problem?

**Comment by MCMicS** [comment]
I believe its a configuration problem. If the error still occurs feel free to reopen the issue
