### ISSUE TITLE
NPE on Startup

### ISSUE THREAD

**Issue by webbasan** [MCMicS/jenkins-control-plugin#297]
I got an NPE after configuring the plugin and restarting IntelliJ IDEA:

stacktrace.txt:
java.lang.NullPointerException
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.isContainParameters(JenkinsJsonParser.java:216)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.lambda$getBuild$0(JenkinsJsonParser.java:190)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.lambda$getBuild$1(JenkinsJsonParser.java:191)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getBuild(JenkinsJsonParser.java:189)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getLastBuild(JenkinsJsonParser.java:372)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:279)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createJobs(JenkinsJsonParser.java:408)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:132)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:345)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.loadJobs(BrowserPanel.java:505)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:478)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

induced.txt:
Following exceptions happened soon after this one, most probably they are induced.

2021-07-08T15:21:02.439
java.lang.NullPointerException
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.isContainParameters(JenkinsJsonParser.java:216)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.lambda$getBuild$0(JenkinsJsonParser.java:190)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.lambda$getBuild$1(JenkinsJsonParser.java:191)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getBuild(JenkinsJsonParser.java:189)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getLastBuild(JenkinsJsonParser.java:372)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:279)
	at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createJobs(JenkinsJsonParser.java:408)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:132)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:345)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.loadJobs(BrowserPanel.java:505)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:478)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

It seems to be related to the "all" View, it re-appears when I select "all", but doesn't happen when I choose a Project View.
But it also appeared after changing the configuration to "Use Green ..."

Additionally, the root note in the View shows as "Jenkins null" -- iI guess that the Plugin expects something different here...

Environment:
- Jenkins 2.277.4
- IntelliJ IDEA Ultimate 2021.1

**Comment by MCMicS** [comment]
Thanks I will have a look at this

**Comment by MCMicS** [comment]
@webbasan Cannot Reproduce it but fix the nullpointer location

Could you please open `https://localhost:8443/api/json?tree=jobs[actions[*]]` and send me the json file

**Comment by MCMicS** [comment]
Could you try following build (2021.2 EAP needed): 
[jenkins-control-plugin-0.13.12-2021.2-eap4.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6803587/jenkins-control-plugin-0.13.12-2021.2-eap4.zip)

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)
