### ISSUE TITLE
Index out of bounds 

### ISSUE THREAD

**Issue by andrebiegel** [MCMicS/jenkins-control-plugin#469]
I installed the plugin and configured it hopefully correctly .. any idea what that could be ? 

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.apache.http.impl.client.RedirectLocations.get(RedirectLocations.java:111)
	at org.apache.http.impl.client.RedirectLocations.get(RedirectLocations.java:44)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.getLastRedirectionHost(DefaultSecurityClient.java:189)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.doAuthentication(BasicSecurityClient.java:61)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.connect(BasicSecurityClient.java:51)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.authenticate(RequestManager.java:294)
	at org.codinjutsu.tools.jenkins.logic.LoginService$1.run(LoginService.java:42)
	at org.codinjutsu.tools.jenkins.logic.JenkinsBackgroundTask.run(JenkinsBackgroundTask.java:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MCMicS** [comment]
Hi thanks for using

on first look it looks like the redirect has a wrong or no location header set.

I can look deeper at this on sunday.
is the server public so i can test against?

If not please try to use `curl -v yourjenkins` and look what the location header says

But I found a issue in code because I not check if redirect locations exists. So it seems to be a bug. I fix it sunday evening and give u a eap version. Is it ok?

**Comment by andrebiegel** [comment]
Actually it is a Server of a Client ... so there Will be no Option to Test against that 
So in the end it Could be that the Client is Filtering something through a waf
But thanks for looking into that .. hopefully my Company is Allowing to install your Build of the Plugin 
Greets from Germany

**Comment by MCMicS** [comment]
Ok
i will provide a fix fast. But I'm currently not at home.

Greets from germany too

**Comment by andrebiegel** [comment]
Do you crawl the Server ? The Client locked my Account .. Maybe an ids triggered something

**Comment by MCMicS** [comment]
No not crawling.
I connect to to and try to reconnect maybe your security locked you out for too many requests.

lets look to it on monday ok?

**Comment by andrebiegel** [comment]
Yeah of Course ... relax

**Comment by MCMicS** [comment]
Hi
can you try following build please: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/324442

**Comment by MCMicS** [comment]
@andrebiegel If problem still exists please reopen issue and provide additional information

**Comment by MCMicS** [comment]
released with [0.13.18](../releases/tag/v0.13.18)
