### ISSUE TITLE
Exception when openin a project

### ISSUE THREAD

**Issue by jacekgajek** [MCMicS/jenkins-control-plugin#495]
This happes when I open a project in which Jenkins is not configured. IntelliJ IDEA 2023.2 Beta (Ultimate Edition).

```
java.lang.IllegalArgumentException: miter limit < 1
	at java.desktop/java.awt.BasicStroke.<init>(BasicStroke.java:201)
	at java.desktop/java.awt.BasicStroke.<init>(BasicStroke.java:249)
	at com.github.weisj.jsvg.M.a(SourceFile:70)
	at com.github.weisj.jsvg.cR.a(SourceFile:237)
	at com.github.weisj.jsvg.be.a(SourceFile:146)
	at com.github.weisj.jsvg.br.a(SourceFile:1094)
	at com.github.weisj.jsvg.br.a(SourceFile:1094)
	at com.github.weisj.jsvg.br.a(SourceFile:1094)
	at com.github.weisj.jsvg.br.a(SourceFile:1094)
	at com.github.weisj.jsvg.bp.a(SourceFile:141)
	at com.github.weisj.jsvg.nodes.SVG.renderWithSize(SourceFile:135)
	at com.intellij.ui.svg.JsvgKt.renderSvgWithSize(jsvg.kt:46)
	at com.intellij.ui.svg.JsvgKt.renderSvg(jsvg.kt:19)
	at com.intellij.ui.svg.JsvgKt.renderSvg$default(jsvg.kt:10)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:309)
	at com.intellij.ui.svg.SvgKt.renderAndCache-rdQnj48(svg.kt:261)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache-rdQnj48(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:590)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:290)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:177)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:139)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:65)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:313)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:119)
	at com.intellij.ui.RowIcon.updateSize(RowIcon.java:170)
	at com.intellij.ui.RowIcon.<init>(RowIcon.java:44)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer$CompositeIcon.<init>(JenkinsTreeRenderer.java:216)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.render(JenkinsTreeRenderer.java:193)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer$1.visit(JenkinsTreeRenderer.java:71)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeNode$JobNode.render(JenkinsTreeNode.java:112)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.render(JenkinsTreeRenderer.java:58)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.lambda$customizeCellRenderer$0(JenkinsTreeRenderer.java:54)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.customizeCellRenderer(JenkinsTreeRenderer.java:54)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:126)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:58)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:189)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:582)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:728)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4407)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:616)
	at java.desktop/javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:400)
	at org.codinjutsu.tools.jenkins.JenkinsTree.lambda$sortJobs$11(JenkinsTree.java:277)
	at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:43)
	at org.codinjutsu.tools.jenkins.JenkinsTree.sortJobs(JenkinsTree.java:277)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.lambda$fillJobTree$2(BrowserPanel.java:582)
	at org.codinjutsu.tools.jenkins.JenkinsTree.keepLastState(JenkinsTree.java:188)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.fillJobTree(BrowserPanel.java:578)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.lambda$onSuccess$0(BrowserPanel.java:543)
	at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:43)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.onSuccess(BrowserPanel.java:542)
	at org.codinjutsu.tools.jenkins.logic.JenkinsBackgroundTask.onSuccess(JenkinsBackgroundTask.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:493)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

```
IntelliJ IDEA 2023.2 Beta (Ultimate Edition)
Build #IU-232.8660.48, built on July 12, 2023
Expiration date: August 11, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-46-generic
Jenkins Plugin 0.13.17-2022.2
GC: G1 Young Generation, G1 Old Generation
Memory: 8048M
Cores: 24
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    IdeaVIM (2.4.0)
    Jenkins Control Plugin (0.13.17-2022.2)
    String Manipulation (9.9.0)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.48)
    woaini.liquibase.plugin (1.3-SNAPSHOT)
    Pythonid (232.8660.48)
    com.intellij.bigdatatools.core (232.8660.48)
    com.intellij.bigdatatools.binary.files (232.8660.48)
    com.intellij.bigdatatools.rfs (232.8660.48)
    com.rspn.git (1.9)
    org.intellij.scala (2023.2.13)

Kotlin: 232-1.8.21-release-380-IJ8660.48
Current Desktop: KDE
```

**Comment by MCMicS** [comment]
Hi see #488
I fixed it with new icons in eap version
https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/365869

But note that with latest 2023.2 also an message is shown for saving setting (#490)

**Comment by MCMicS** [comment]
new EAP for 2023.2: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/367055

**Comment by MCMicS** [comment]
released with 0.13.18: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/367700

**Comment by jacekgajek** [comment]
No exception but it's colors are inverted.
![image](https://github.com/MCMicS/jenkins-control-plugin/assets/68021034/ad8a3e78-8c84-4311-965f-f2d58e238a27)

```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to Jacek Gajek
You have a perpetual fallback license for this version.
Subscription is active until July 29, 2024.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-50-generic
Jenkins Plugin 0.13.18-2023.2
GC: G1 Young Generation, G1 Old Generation
Memory: 8000M
Cores: 24
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    de.netnexus.camelcaseplugin (3.0.12)
    IdeaVIM (2.4.1)
    org.turbanov.run.configuration.as.action (1.5.1)
    commit-prefix-plugin (1.2.1)
    com.github.stevejagodzinski.akka-log-inspection-plugin (1.2.9)
    Jenkins Control Plugin (0.13.18-2023.2)
    String Manipulation (9.10.0)
    woaini.liquibase.plugin (1.3-SNAPSHOT)
    PlantUML integration (6.3.0-IJ2023.2)
    dev.nx.console (1.10.0)
    com.github.iguissouma.nxconsole (0.58.0)
    Pythonid (232.8660.185)
    com.rspn.git (1.9)
    kotest-plugin-intellij (1.3.69-IC-232-EAP-SNAPSHOT)
    com.intellij.ml.llm (232.9353)
    org.intellij.scala (2023.2.17)
    zio.intellij.zio-intellij (2023.2.27.0)
    aws.toolkit (1.74-232)
    org.jetbrains.plugins.docker.gateway (232.8660.202)

Kotlin: 232-1.9.0-IJ8660.185
Current Desktop: KDE
```

**Comment by MCMicS** [comment]
Thanks for report
I didn't test dark UI with new icon. I'll fix it
