### ISSUE TITLE
IDE error if previously-working Jenkins server becomes unavailable.

### ISSUE THREAD

**Issue by smheaton** [MCMicS/jenkins-control-plugin#75]
I have a previously configured Jenkins server that was working fine.  We took the server down for maintenance (it now returns a 503).  When I launch IntelliJ 13.1.1, I get an IDE Fatal Error:

8:44:11 PM IllegalStateException: Empty JSON data!: Empty JSON data!

Stacktrace from error message:

Empty JSON data!: Empty JSON data!
java.lang.IllegalStateException: Empty JSON data!
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.checkJsonDataAndThrowExceptionIfNecessary(JenkinsJsonParser.java:345)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createWorkspace(JenkinsJsonParser.java:36)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsWorkspace(RequestManager.java:75)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.reloadConfiguration(BrowserPanel.java:343)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.init(BrowserPanel.java:363)
    at org.codinjutsu.tools.jenkins.JenkinsWindowManager$1.run(JenkinsWindowManager.java:72)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:259)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:176)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$4$2.run(ProjectManagerImpl.java:446)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by MCMicS** [comment]
relates to #109

**Comment by smheaton** [comment]
Closing old, probably outdated issue.
